### ISSUE TITLE
关于匹配规则的建议

### ISSUE THREAD

**Issue by KarisAya** [Cvandia/nonebot-plugin-whateat-pic#1]
^((今天|明天)|(今天|明天)?(早上|晚上|中午|夜宵))吃什么$
匹配吃什么
^((今天|明天)|(今天|明天)?(早上|晚上|中午|夜宵))喝什么$
匹配喝什么

防止一些误触发

**Comment by Cvandia** [comment]
> ^((今天|明天)|(今天|明天)?(早上|晚上|中午|夜宵))吃什么$ 匹配吃什么 ^((今天|明天)|(今天|明天)?(早上|晚上|中午|夜宵))喝什么$ 匹配喝什么
> 
> 防止一些误触发

可以的，我第一次接触匹配机制，还不熟悉，谢谢指点（｡ò ∀ ó｡）

**Comment by Cvandia** [comment]
下午更新点图片，顺便改下ヾ(￣▽￣)
