### ISSUE TITLE
[建议]希望可以添加对超过whateat_max次数限制的人的回复

### ISSUE THREAD

**Issue by ElaineOwO** [Cvandia/nonebot-plugin-whateat-pic#10]
比如：你今天已经吃的够多了！ 之类的qwq

**Comment by Cvandia** [comment]
哦~原来是这样呀，语言要生动点？>3<，那我加个回复的

**Comment by ElaineOwO** [comment]
> 哦~原来是这样呀，语言要生动点？>3<，那我加个回复的

噢！感谢大佬

**Comment by ElaineOwO** [comment]
> 感谢大佬的更新！，但是不知道为什么nb plugin install下载的是旧版。。要从仓库手动下载替换才行

原来我用的是清华源，，我是bakaQWQ

**Comment by Cvandia** [comment]
> > 感谢大佬的更新！，但是不知道为什么nb plugin install下载的是旧版。。要从仓库手动下载替换才行
> 
> 原来我用的是清华源，，我是bakaQWQ

我刚想回复来着……
