### ISSUE TITLE
添加菜单和删除菜单功能异常

### ISSUE THREAD

**Issue by hakunomiko** [Cvandia/nonebot-plugin-whateat-pic#16]
使用的是1.4.8版本，前端使用的NapCatQQ3.6.4。
添加菜品功能没有报错，但是发现最后会在.\data\whateat_pic\eat_pic文件夹下创建一个只有文件名没有后缀名的文件，还没有测试是否能够正常获得这个菜品。
而删除菜品会直接提示删除失败，同样没有报错。
还有个小问题，使用“查看菜单菜单”这种格式的命令可以正常查看所有菜单，而使用“全部菜单菜单”这种格式的命令则不会响应，必须使用“全部菜单 菜单”才可以，不确定是什么原因。

**Comment by Cvandia** [comment]
`必须使用“全部菜单 菜单”`是因为alconna命令解析需要空格作为参数分离，`没有后缀名`已定位到问题，下个版本更新

**Comment by hakunomiko** [comment]
> `必须使用“全部菜单 菜单”`是因为alconna命令解析需要空格作为参数分离，`没有后缀名`已定位到问题，下个版本更新

好的，辛苦大佬

**Comment by Cvandia** [comment]
@hakunomiko 更新到1.5.0版本解决问题

**Comment by Cvandia** [comment]
@xiaoWangSec 更新至1.5.1解决问题

**Comment by xiaoWangSec** [comment]
> @xiaoWangSec 更新至1.5.1解决问题

怎么点给我了

**Comment by Cvandia** [comment]
> > @xiaoWangSec 更新至1.5.1解决问题
> 
> 怎么点给我了
😋

**Comment by hakunomiko** [comment]
> ~@xiaoWangSec~ 更新至1.5.1解决问题

收到，问题已解决，辛苦了。
