### ISSUE TITLE
是否可以将正则修改成可以匹配“今早吃什么”“今晚吃什么”，感觉挺常用的

### ISSUE THREAD

**Issue by 765934919** [Cvandia/nonebot-plugin-whateat-pic#18]
`r"^[今|明|后]?[天|日]?(早|中|晚)?(上|午|餐|饭|夜宵|宵夜)吃(什么|啥|点啥)$"`
修改成
r"^(今|明|后)?(天|日)?(早|中|晚)?(上|午|餐|饭|夜宵|宵夜)?吃(什么|啥|点啥)$"
或者用这种来规避一个“吃什么”就触发？
"^(今|明|后|天|日|早|中|晚|上|午|餐|饭|夜宵|宵夜)+吃(什么|啥|点啥)$"

**Comment by Cvandia** [comment]
对应修改为`^[今|明|后]?[天|日]?(早|中|晚)?(上|午|餐|饭|夜宵|宵夜|早|晚)吃(什么|啥|点啥)$`即可
