### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by qixiabanyi** [Cvandia/nonebot-plugin-whateat-pic#19]
重装后并使用默认配置无法使用
![屏幕截图 2024-11-23 165550](https://github.com/user-attachments/assets/83143753-4b72-45fc-9255-58ccad03c532)
![屏幕截图 2024-11-23 165555](https://github.com/user-attachments/assets/cb657517-d7fc-4111-9dca-b709eb2b8f8f)

**Comment by Cvandia** [comment]
是否尝试过使用其他ob11的实现端，如：`Lagrange`和`Napcat`

**Comment by qixiabanyi** [comment]
没有
&nbsp;


3479637514
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月23日(星期六) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cvandia/nonebot-plugin-whateat-pic] 无法使用 (Issue #19)














 
是否尝试过使用其他ob11的实现端，如：Lagrange和Napcat

**Comment by Cvandia** [comment]
测试最新版没有问题，请更新至最新版`LLonebot`
