### ISSUE TITLE
这个cd是不是有点问题

### ISSUE THREAD

**Issue by fllesser** [Cvandia/nonebot-plugin-whateat-pic#24]
![1733287339545_edit_42295492057607.jpg](https://github.com/user-attachments/assets/f45998f9-086c-4fdd-bce7-5d9724ad09ac)

**Comment by Cvandia** [comment]
~~可能cd太短了~~好的，cd是多少，我好复现一下

**Comment by fllesser** [comment]
> ~~可能cd太短了~~好的，cd是多少，我好复现一下

默认的，我没设置

**Comment by Cvandia** [comment]
更新到最新版[v1.5.4](https://github.com/Cvandia/nonebot-plugin-whateat-pic/releases/tag/v1.5.4)试试

**Comment by fllesser** [comment]
👌
