### ISSUE TITLE
插件不响应命令

### ISSUE THREAD

**Issue by HL-Light** [Cvandia/nonebot-plugin-whateat-pic#4]
![image](https://user-images.githubusercontent.com/116658416/222671574-8be3582a-6788-447c-bd8b-5ee36a83675c.png)
已经确认加载，对比如/今天吃什么 吃什么 和不加/都没反应，我机器人是命令识别设置是
![image](https://user-images.githubusercontent.com/116658416/222671832-9fcbdeb1-8f29-4a2a-b68a-21ce918858f9.png)

**Comment by Cvandia** [comment]
明白了，是正则匹配的问题，或许试试```今天早上吃什么```能响应，因为之前考虑到```今天吃什么```太笼统了

**Comment by Cvandia** [comment]
如果实在想要匹配```今天吃什么```，可将原正则表达式该部分```(上|午|餐|饭|夜宵|宵夜)吃(什么|啥|点啥)```改为```(上|午|餐|饭|夜宵|宵夜)?吃(什么|啥|点啥)```

**Comment by HL-Light** [comment]
可以了！原来是这样，已解决
