### ISSUE TITLE
希望增加每日使用次数功能

### ISSUE THREAD

**Issue by yuukia0** [Cvandia/nonebot-plugin-whateat-pic#5]
希望增加每日使用次数功能，以及两次使用间隔，避免刷屏~

**Comment by Cvandia** [comment]
可以的，下个版本在完善```删除菜单```的时候添加```内置cd```的功能，但是每天限制次数是否也太...qwq

**Comment by yuukia0** [comment]
> 可以的，下个版本在完善`删除菜单`的时候添加`内置cd`的功能，但是每天限制次数是否也太...qwq

每天限制次数防止群友吃太多或者一直ROLL，可以考虑自定义次数，填0不限制，每日定时刷新 ╰(*°▽°*)╯

**Comment by Cvandia** [comment]
已采纳，请更新到最新版本哦~
