### ISSUE TITLE
关于修改```查看全部菜单```的改进

### ISSUE THREAD

**Issue by Cvandia** [Cvandia/nonebot-plugin-whateat-pic#6]
打算取消合并转发，通过```图片```的方式发送菜单（不含菜品图片)[源码在这儿](https://github.com/Cvandia/nonebot-plugin-whateat-pic/blob/main/nonebot_plugin_whateat_pic/__init__.py)，或者添加可选择配置```图片or合并转发```，给个建议，哪个更好点? (@^@)

**Comment by yuukia0** [comment]
可选择配置比较好
